### ISSUE TITLE
LST matlab tool issue

### ISSUE THREAD

**Issue by sj-choi** [eebrown/LST#3]
It has been working well without an issue. 
Recently, I encountered the following error:

Error using fprintf
Invalid file identifier. Use fopen to generate a valid file identifier.
In file "/home/xubuntu/spm12/toolbox/LST/ps_LST_lpa.m" (???), function "ps_LST_lpa" at line 117.

The following modules did not run:
Failed: LST: Lesion segmentation (LPA)

However, the files do not have any issues. They are nii files, not compressed. 
I tried to process other sets of files that had previously been processed successfully with LST. However, I encountered the same error. I am confused.

Could you explain what might be the issue? 

Sincerely,
-SC

**Comment by eebrown** [comment]
This is just a mirror and the developers do not monitor this repository.

**Comment by sj-choi** [comment]
Could you let me know where I should visit, then?

**Comment by eebrown** [comment]
https://www.applied-statistics.de/lst.html

**Comment by sj-choi** [comment]
Thank you.
